
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label1;

	private global::Gtk.HScale bpmSlider;

	private global::Gtk.Button playbackButton;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label2;

	private global::Gtk.HScale masterVolumeSlider;

	private global::Gtk.HBox hbox3;

	private global::Gtk.HBox hbox4;

	private global::Gtk.HPaned hpaned1;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button claveButton;

	private global::Gtk.ComboBox combobox1;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Button cowbellButton;

	private global::Gtk.ComboBox combobox2;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Button bongosButton;

	private global::Gtk.ComboBox combobox3;

	private global::Gtk.VBox vbox3;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Salsa Musicality");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("BPM");
		this.hbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.bpmSlider = new global::Gtk.HScale(null);
		this.bpmSlider.CanFocus = true;
		this.bpmSlider.Name = "bpmSlider";
		this.bpmSlider.Adjustment.Lower = 100D;
		this.bpmSlider.Adjustment.Upper = 250D;
		this.bpmSlider.Adjustment.PageIncrement = 10D;
		this.bpmSlider.Adjustment.StepIncrement = 1D;
		this.bpmSlider.Adjustment.Value = 100D;
		this.bpmSlider.DrawValue = true;
		this.bpmSlider.Digits = 0;
		this.bpmSlider.ValuePos = ((global::Gtk.PositionType)(2));
		this.hbox1.Add(this.bpmSlider);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.bpmSlider]));
		w2.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.playbackButton = new global::Gtk.Button();
		this.playbackButton.CanFocus = true;
		this.playbackButton.Name = "playbackButton";
		this.playbackButton.UseUnderline = true;
		this.playbackButton.Label = global::Mono.Unix.Catalog.GetString("Play");
		this.hbox1.Add(this.playbackButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.playbackButton]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Master Volume");
		this.hbox2.Add(this.label2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label2]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.masterVolumeSlider = new global::Gtk.HScale(null);
		this.masterVolumeSlider.CanFocus = true;
		this.masterVolumeSlider.Name = "masterVolumeSlider";
		this.masterVolumeSlider.Adjustment.Upper = 10D;
		this.masterVolumeSlider.Adjustment.PageIncrement = 10D;
		this.masterVolumeSlider.Adjustment.StepIncrement = 0.1D;
		this.masterVolumeSlider.Adjustment.Value = 1D;
		this.masterVolumeSlider.DrawValue = true;
		this.masterVolumeSlider.Digits = 0;
		this.masterVolumeSlider.ValuePos = ((global::Gtk.PositionType)(2));
		this.hbox2.Add(this.masterVolumeSlider);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.masterVolumeSlider]));
		w6.Position = 1;
		this.vbox2.Add(this.hbox2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		this.vbox2.Add(this.hbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
		w8.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 10;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.claveButton = new global::Gtk.Button();
		this.claveButton.CanFocus = true;
		this.claveButton.Name = "claveButton";
		global::Gtk.Image w9 = new global::Gtk.Image();
		this.claveButton.Image = w9;
		this.hbox5.Add(this.claveButton);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.claveButton]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.combobox1 = global::Gtk.ComboBox.NewText();
		this.combobox1.Name = "combobox1";
		this.hbox5.Add(this.combobox1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.combobox1]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.hpaned1.Add(this.hbox5);
		this.hbox4.Add(this.hpaned1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hpaned1]));
		w13.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.cowbellButton = new global::Gtk.Button();
		this.cowbellButton.CanFocus = true;
		this.cowbellButton.Name = "cowbellButton";
		this.cowbellButton.UseUnderline = true;
		global::Gtk.Image w14 = new global::Gtk.Image();
		this.cowbellButton.Image = w14;
		this.hbox6.Add(this.cowbellButton);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.cowbellButton]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.combobox2 = global::Gtk.ComboBox.NewText();
		this.combobox2.Name = "combobox2";
		this.hbox6.Add(this.combobox2);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.combobox2]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.hbox4.Add(this.hbox6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox6]));
		w17.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.bongosButton = new global::Gtk.Button();
		this.bongosButton.CanFocus = true;
		this.bongosButton.Name = "bongosButton";
		global::Gtk.Image w18 = new global::Gtk.Image();
		this.bongosButton.Image = w18;
		this.hbox7.Add(this.bongosButton);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.bongosButton]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.combobox3 = global::Gtk.ComboBox.NewText();
		this.combobox3.Name = "combobox3";
		this.hbox7.Add(this.combobox3);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.combobox3]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		this.hbox4.Add(this.hbox7);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox7]));
		w21.Position = 2;
		this.vbox2.Add(this.hbox4);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
		w22.Position = 3;
		w22.Expand = false;
		w22.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w23.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		this.vbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
		w24.Position = 2;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 722;
		this.DefaultHeight = 749;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.bpmSlider.ValueChanged += new global::System.EventHandler(this.OnBpmSliderValueChanged);
		this.playbackButton.Clicked += new global::System.EventHandler(this.OnPlaybackButtonClicked);
		this.masterVolumeSlider.ValueChanged += new global::System.EventHandler(this.OnMasterVolumeSliderChanged);
		this.claveButton.Clicked += new global::System.EventHandler(this.OnClaveButtonClicked);
		this.cowbellButton.Clicked += new global::System.EventHandler(this.OnCowbellButtonClicked);
		this.bongosButton.Clicked += new global::System.EventHandler(this.OnBongosButtonClicked);
	}
}
